# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testp

  target 'testpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testpUITests' do
    # Pods for testing
  end
platform :ios, '10.0'
use_frameworks!
pod 'TextFieldCounter'
end
